before_install:
    - echo $GPG_SECRET_KEYS | openssl base64 -d | gpg --import
    - echo $GPG_OWNERTRUST | openssl base64 -d | gpg --import-ownertrust
language: java
install:
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
sudo: disable
git:
  depth: 500
on:
  tags: true
