before_install:
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
language: java
script: mvn clean install
sudo: disable
git:
  depth: 500
on:
  tags: true
branches:
  only: 
    - master
